### ISSUE TITLE
您好啊

### ISSUE THREAD

**Issue by mizuhara37** [laosb/ama#2]
偶然间看到你follow了我，并且发现我们都是宁波人，我们之间也有这好多好多相同的经历，我想和你加一下联系方式...

**Comment by laosb** [comment]
> 偶然间看到你follow了我，并且发现我们都是宁波人，我们之间也有这好多好多相同的经历，我想和你加一下联系方式...

請透過GitHub上的電郵私下聯絡我，並表明您個人使用的聯絡方式。
